version: "3.7"
services:
  db-mongo:
    image: "public.ecr.aws/docker/library/mongo:3"
    healthcheck:
      test: ["CMD-SHELL", 'mongo --eval ''db.runCommand("ping").ok'' localhost:27017/test --quiet']
      interval: 10s
      timeout: 2s
      retries: 10
    ports:
      - "27017:27017"
